### PR TITLE
Puppeteer Setup

### LINKED ISSUE #51: Puppeteer Setup
Setting up puppeteer, making some end 2 end tests for the projects and notes pages

### PR DESCRIPTION
**Pull request by mattqgoldberg**
Added devDependencies from the lab:
babel, puppeteer, jest-puppeteer

Added dependencies for running a server:
webpack-dev-server, webpack-cli, html-loader

Changed github action to include a server to run puppeteer tests

Added one dummy test to check for success of server running and it passed

closes #51

### CODE REVIEW

**Comment by mattqgoldberg** [comment]
Not sure why the dist folder is still there working on fixing that

**Comment by mattqgoldberg** [comment]
Fixed

**Review by thedonutdan — COMMENTED** [review]
I think it would be good to separate end2end testing and unit testing in order to have more granular clarity on what status checks are failing.
We can also configure the scripts section in package.json to include a script for puppeteer that can be run using npm run locally so team members can easily test locally before pushing

**Review by thedonutdan — COMMENTED** [review]
Looks great!

**Review by thedonutdan — APPROVED** [review]
Looks great!

**Pull request merged**
