### PR TITLE
Project notes page task list

### PR DESCRIPTION
**Pull request by vaibhavmaloo03**
To add task list functionality to the project notes page

### CODE REVIEW

**Comment by vaibhavmaloo03** [comment]
closing pull request since tests did not pass

**Comment by mattqgoldberg** [comment]
You can keep the PR open in the future
Every time you make a commit it will rerun the tests until they are good

**Review by thedonutdan — CHANGES_REQUESTED** [review]
It's looking good! Had to update the link tag in notes.html for notes.js to identify it as type module for puppeteer testing.
Requested changes: This is a good chance to add a puppeteer test for the task list. You will likely have to include type="module" in the link tag for todo.js for this.
Once the E2E test for this feature passes we can merge over

**Comment by vaibhavmaloo03** [comment]
> It's looking good! Had to update the link tag in notes.html for notes.js to identify it as type module for puppeteer testing. Requested changes: This is a good chance to add a puppeteer test for the task list. You will likely have to include type="module" in the link tag for todo.js for this. Once the E2E test for this feature passes we can merge over

sounds good, will do that

**Review by thedonutdan — APPROVED** [review]

**Pull request merged**
