### PR TITLE
Pwa and service worker 

### PR DESCRIPTION
**Pull request by Person1234565**

### CODE REVIEW

**Review by thedonutdan — COMMENTED** [review]
I'm getting some errors after I pulled this to my local and tried to test the PWA. I'm using Edge and getting this error:
```
newfolder.png:1 
   
        
        GET http://127.0.0.1:59674/assets/images/newfolder.png 404 (Not Found)
project.html:1  Error while trying to use the following icon from the Manifest: http://127.0.0.1:59674/assets/images/newfolder.png (Download error or resource isn't a valid image)
```
Did you get it working in another browser?

**Comment by Person1234565** [comment]
> I'm getting some errors after I pulled this to my local and tried to test the PWA. I'm using Edge and getting this error:
> 
> ```
> newfolder.png:1 
>    
>         
>         GET http://127.0.0.1:59674/assets/images/newfolder.png 404 (Not Found)
> project.html:1  Error while trying to use the following icon from the Manifest: http://127.0.0.1:59674/assets/images/newfolder.png (Download error or resource isn't a valid image)
> ```
> 
> Did you get it working in another browser?



> I'm getting some errors after I pulled this to my local and tried to test the PWA. I'm using Edge and getting this error:
> 
> ```
> newfolder.png:1 
>    
>         
>         GET http://127.0.0.1:59674/assets/images/newfolder.png 404 (Not Found)
> project.html:1  Error while trying to use the following icon from the Manifest: http://127.0.0.1:59674/assets/images/newfolder.png (Download error or resource isn't a valid image)
> ```
> 
> Did you get it working in another browser?

I don't get this error on Chrome I think

**Comment by Person1234565** [comment]
NVM I think I found the issue, strange that chrome didn't give me any errors.

**Comment by mattqgoldberg** [comment]
works fine on both chrome and edge for me, a couple things though, are we planning on removing the download app button from the homepage or making it work with the install PWA, also it feels a bit weird that after you install the PWA it opens up the landing page that says launch in browser/download

**Comment by thedonutdan** [comment]
We could probably go ahead and set the app to just display the project page

**Review by thedonutdan — APPROVED** [review]
In my testing it defaults to the project page as expected and seems to work. We should get this integrated now so we can deploy it, test it, and ensure it is working across targeted devices.

**Pull request merged**
