### PR TITLE
Notes revamp

### PR DESCRIPTION
**Pull request by Person1234565**
Revamped the notes section of the notes page, task list part still in progress

### CODE REVIEW

**Review by thedonutdan — COMMENTED** [review]
We'll have to update the puppeteer and unit testing since we changed the format of the note

**Review by thedonutdan — CHANGES_REQUESTED** [review]
Looks great! One thing, long notes are cut off. We should implement some mechanism to show the start of a note and give the option to expand it if it is longer than some threshold

**Comment by Person1234565** [comment]
There should be a More button on long notes which expand them.

**Comment by thedonutdan** [comment]
> There should be a More button on long notes which expand them. image
> 
> image

Not showing up on my end. what browser are you using?
Screenshot (17)

**Comment by Person1234565** [comment]
That's strange. Right now I'm using Chrome

**Comment by thedonutdan** [comment]
Let me try firefox

**Comment by thedonutdan** [comment]
Note to self: Pull often

**Review by thedonutdan — APPROVED** [review]
You're a rockstar!

**Pull request merged**
